name: Continous Deploy Docker Container on main branch

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login into Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t tandat1508/my-todo-app:latest .

      - name: Push image to Docker Hub
        run: docker push tandat1508/my-todo-app:latest

  deploy:
    runs-on: self-hosted
    steps:
      - name: Debug info
        run: |
          whoami
          id
          groups

      - name: Pull image from Docker Hub
        run: docker pull tandat1508/my-todo-app:latest

      - name: Stop previous Container
        run: |
          docker stop docker-ci-cd || true
          docker rm docker-ci-cd || true

      - name: Run new Container
        run: |
          docker run -d --name docker-ci-cd -p 4567:4567 tandat1508/my-todo-app:latest
